; ============================================================================
; Void Strike 65 — the disk guard (audit-hardening, AUD-01 / AUD-02)
; ============================================================================
;
; docs/plans/audit-hardening.md §2-§3, owner decisions of 2026-10-07 and the
; owner's answers Q1-Q3. Included at the end of src/hybrid/light-kernel.s, in
; a segment of its own behind the kernel: it rides the Light kernel's DFMC
; record, so the boot's CRC16 vouches for every byte here, and it is resident
; from the boot to RESET. Nothing in the gameplay frame calls it.
;
; A load at a transition is used only once its run checks: the reader folds
; every sector it accepts into a 16-bit Fletcher sum of the sectors' SIO
; carry-wrap sums (a += s; b += a with a's carry), and the run is compared with
; the value the build computed from the same bytes. A run from another disk,
; or a damaged one, fails before a byte of it is run or used (owner Q1: this
; is the load-time identity check). The record (directory entry 7) is the one
; run never checked: the game writes it.
;
; The identity block is the six bytes the build writes at the start of the
; disk's identity sector (598): "VS65" and the layout id. The summary reads
; that sector before every PUT and compares it with these bytes (AUD-01).
;
; The expected values are only known once every run has linked, so the build
; links the kernel once with zeros here and once more with the values; the
; second link may change no label and no byte outside guard_sums (checked).

; The reader's status codes (src/hybrid/sector-reader.s).
GUARD_SR_OK        = 0
GUARD_SR_BAD_IMAGE = 4              ; the failure screen's WRONG DISK

; GUARD_ENTRIES, GUARD_RECORD_ENTRY, GUARD_IDENTITY_BYTES and the two data
; macros, generated by scripts/build.mjs.
.include "disk-guard-sums.inc"

.segment "DISK_GUARD"

; X = the overlay directory entry a run read is about to read. X is kept.
guard_begin:
        stx guard_entry
; The fold starts again. X and Y are kept.
guard_reset:
        lda #$00
        sta guard_sum
        sta guard_sum+1
        rts

; A = the carry-wrap sum of a sector the reader accepted. X and Y are kept.
guard_fold:
        clc
        adc guard_sum
        sta guard_sum
        adc guard_sum+1
        sta guard_sum+1
        rts

; The run guard_begin named against its expected value.
;   C=0, A=GUARD_SR_OK          it checks (or it is the record)
;   C=1, A=GUARD_SR_BAD_IMAGE   it does not
guard_check:
        lda guard_entry
        cmp #GUARD_RECORD_ENTRY
        beq guard_ok
        asl
        tax
        lda guard_sums+1,x
        tay
        lda guard_sums,x
; A/Y = an expected value, lo/hi, against the fold so far. Same result.
guard_compare:
        cmp guard_sum
        bne guard_bad
        cpy guard_sum+1
        bne guard_bad
guard_ok:
        lda #GUARD_SR_OK
        clc
        rts
guard_bad:
        lda #GUARD_SR_BAD_IMAGE
        sec
        rts

; The expected value of each directory entry's run, lo/hi.
guard_sums:
        GUARD_SUM_TABLE
; The identity block the disk's identity sector must start with.
guard_identity:
        GUARD_IDENTITY_BLOCK
guard_entry:
        .byte $00
guard_sum:
        .byte $00, $00
guard_end:

.assert guard_identity - guard_sums = GUARD_ENTRIES * 2, error, "the guard's table is not one value per directory entry"
.assert guard_entry - guard_identity = GUARD_IDENTITY_BYTES, error, "the identity block is not GUARD_IDENTITY_BYTES"
; Its end against $BC00 is light-kernel.s's __LIGHT_KERNEL_RAM_LAST__ assert:
; the guard's segment is the last in that memory area (cfg/light-kernel.cfg).

.export guard_begin, guard_reset, guard_fold, guard_check, guard_compare
.export guard_sums, guard_identity, guard_entry, guard_sum
