// audit-hardening (docs/plans/audit-hardening.md §2-§3): the build's half of
// the disk guard (src/hybrid/disk-guard.s) - the fold the reader computes over
// a run, the disk's identity block, and the generated includes that carry the
// expected values into the resident guard, the summary module and slot A.
import crypto from "node:crypto";

export const SECTOR_BYTES = 128;
export const IDENTITY_MAGIC = "VS65";
export const IDENTITY_BYTES = 6;

// The SIO frame checksum of one sector (HRM ch.9 p.217), as the reader's
// receive loop computes it into sr_checksum.
export function carryWrapSum(bytes) {
  let sum = 0;
  for (const byte of bytes) {
    sum += byte;
    if (sum > 0xff) sum = (sum & 0xff) + 1;
  }
  return sum & 0xff;
}

// guard_fold over the sectors of `data` (whole sectors; a short tail reads as
// the zeros the ATR holds after it), continuing from `state`:
//   clc; adc a; sta a; adc b; sta b
export function guardFold(data, state = { lo: 0, hi: 0 }) {
  let { lo, hi } = state;
  const sectors = Math.ceil(data.length / SECTOR_BYTES);
  for (let index = 0; index < sectors; index += 1) {
    const sector = Buffer.alloc(SECTOR_BYTES);
    Buffer.from(data.subarray(index * SECTOR_BYTES, (index + 1) * SECTOR_BYTES)).copy(sector);
    const sum = lo + carryWrapSum(sector);
    lo = sum & 0xff;
    hi = (hi + lo + (sum > 0xff ? 1 : 0)) & 0xff;
  }
  return { lo, hi };
}

// The level read's order (src/hybrid/sector-reader.s sector_reader_load): the
// sectors after the five-sector head first, then the head.
export function levelReadOrder(image, headSectors = 5) {
  const sectors = Math.ceil(image.length / SECTOR_BYTES);
  const padded = Buffer.alloc(sectors * SECTOR_BYTES);
  Buffer.from(image).copy(padded);
  if (sectors <= headSectors) return padded;
  return Buffer.concat([padded.subarray(headSectors * SECTOR_BYTES), padded.subarray(0, headSectors * SECTOR_BYTES)]);
}

// The layout id: what the layout reserves, never what a build put there, so
// it is the same for every build of one layout and every copy of its ATR.
export function layoutId(layout) {
  const canonical = JSON.stringify(Object.keys(layout).sort().map((key) => [key, layout[key]]));
  return crypto.createHash("sha256").update(canonical).digest().readUInt16LE(0);
}

export function identityBlock(layout) {
  const id = layoutId(layout);
  return Buffer.concat([Buffer.from(IDENTITY_MAGIC, "latin1"), Buffer.from([id & 0xff, id >> 8])]);
}

export function identitySector(layout) {
  const sector = Buffer.alloc(SECTOR_BYTES);
  identityBlock(layout).copy(sector);
  return sector;
}

const hex = (value) => `$${(value & 0xff).toString(16).toUpperCase().padStart(2, "0")}`;
const sumLine = ({ lo, hi }, note) => `        .byte ${hex(lo)}, ${hex(hi)}\t; ${note}`;

// The resident guard's include: one expected value per directory entry, and
// the identity block. `sums` is null for the first link (zeros).
export function renderGuardInclude({ names, recordEntry, sums = null, identity }) {
  return [
    "; Generated by scripts/build.mjs (audit-hardening) - do not edit.",
    "; The expected fold of each overlay directory entry's run, and the identity",
    "; block of the disk's identity sector (src/hybrid/disk-guard.s).",
    `GUARD_ENTRIES = ${names.length}`,
    `GUARD_RECORD_ENTRY = ${recordEntry}`,
    `GUARD_IDENTITY_BYTES = ${identity.length}`,
    ".macro GUARD_SUM_TABLE",
    ...names.map((name, index) => sumLine(sums?.[index] ?? { lo: 0, hi: 0 },
      `${index}: ${name}${index === recordEntry ? " (never checked)" : ""}`)),
    ".endmacro",
    ".macro GUARD_IDENTITY_BLOCK",
    `        .byte ${[...identity].map(hex).join(", ")}`,
    ".endmacro",
    "",
  ].join("\n");
}

// A table of expected values for a link that checks its own reads (the
// summary's art and levels, slot A's head), indexed by X without doubling:
// `${label}_lo` then `${label}_hi`, one byte per entry each.
export function renderSumTable(label, entries) {
  const half = (part) => [
    `${label}_${part}:`,
    ...entries.map(({ sum, note }) => `        .byte ${hex((sum ?? { lo: 0, hi: 0 })[part])}\t; ${note}`),
  ];
  return [...half("lo"), ...half("hi"), ""].join("\n");
}
